print("Simulation Branch Checkout ")
print("Lab 1: Version Control")
print("Author: Rachel Angel H. David")
print("Student ID: TUPM-26-1110")
print("Class Section: SIMULATION ")
print("Login Feature Enabled")
